language: node_js
node_js:
  - "8"
cache:
  yarn: true
directories:
  - node_modules
script: timeout=6000 npm run test
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"